<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Product>
 */
class ProductFactory extends Factory
{
    /**
     * Define the model's default state.
     *
    * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            "categories_id" => fake()->numberBetween(1,6),
            "name" => fake()->sentence(6,true),
            "description" => fake()->sentences(10,true),
            "price" => fake()->numberBetween(300,300000),
            "image"=> fake()->randomElement(['/images/faker/1.jpg',
                                              '/images/faker/2.jpg',
                                              '/images/faker/3.jpg',
                                              '/images/faker/4.jpg',
                                              '/images/faker/5.jpg',
                                              '/images/faker/6.jpg',
                                              '/images/faker/7.jpg',
                                              '/images/faker/8.jpg',
                                              '/images/faker/9.jpg',
                                              '/images/faker/10.jpg',
                                              '/images/faker/11.jpg',
                                              '/images/faker/12.jpg',
                                              '/images/faker/13.jpg',
                                              '/images/faker/14.jpg',
                                              '/images/faker/15.jpg',
                                              '/images/faker/16.jpg',
                                              '/images/faker/17.jpg',
                                              '/images/faker/18.jpg',
                                              '/images/faker/19.jpg',
                                              '/images/faker/20.jpg',
                                              '/images/faker/21.jpg',
                                              '/images/faker/22.jpg',
                                              '/images/faker/23.jpg',
                                              '/images/faker/24.jpg',
                                              '/images/faker/25.jpg',
                                              '/images/faker/26.jpg',
                                              '/images/faker/27.jpg',
                                              '/images/faker/28.jpg',
                                              '/images/faker/29.jpg',
                                              '/images/faker/30.jpg',
                                              '/images/faker/31.jpg',
                                              '/images/faker/32.jpg',
                                              '/images/faker/33.jpg',
                                              '/images/faker/34.jpg',
                                              '/images/faker/35.jpg',
                                              '/images/faker/36.jpg',
                                              '/images/faker/37.jpg',
                                              '/images/faker/38.jpg',
                                              '/images/faker/39.jpg',
                                              '/images/faker/40.jpg',
                                              '/images/faker/41.jpg',
                                              '/images/faker/42.jpg',
                                              '/images/faker/43.jpg',
                                              '/images/faker/44.jpg',
                                              '/images/faker/45.jpg',
                                              '/images/faker/46.jpg',
                                              '/images/faker/47.jpg',
                                              '/images/faker/48.jpg',
                                              '/images/faker/49.jpg',
                                              '/images/faker/50.jpg',
                                              '/images/faker/51.jpg',
                                              '/images/faker/52.jpg',
                                              '/images/faker/53.jpg',
                                              '/images/faker/54.jpg',
                                              '/images/faker/55.jpg',
                                              '/images/faker/56.jpg',
                                              '/images/faker/57.jpg',
                                              '/images/faker/58.jpg',
                                              '/images/faker/59.jpg',
                                              '/images/faker/60.jpg',
                                              '/images/faker/61.jpg',
                                              '/images/faker/62.jpg',
                                              '/images/faker/63.jpg',
                                              '/images/faker/64.jpg',
                                              '/images/faker/65.jpg',
                                              '/images/faker/66.jpg',
                                              '/images/faker/67.jpg',
                                              '/images/faker/68.jpg',
                                              '/images/faker/69.jpg',
                                              '/images/faker/70.jpg',
                                              '/images/faker/71.jpg',
                                              '/images/faker/72.jpg',
                                              '/images/faker/73.jpg',
                                              '/images/faker/74.jpg',
                                              '/images/faker/75.jpg',
                                              '/images/faker/76.jpg',
                                              '/images/faker/77.jpg',
                                              '/images/faker/78.jpg',
                                              '/images/faker/79.jpg',
                                              '/images/faker/80.jpg',
                                              '/images/faker/81.jpg',
                                              '/images/faker/82.jpg',
                                              '/images/faker/83.jpg',
                                              '/images/faker/84.jpg',
                                              '/images/faker/85.jpg',
                                              '/images/faker/86.jpg',
                                              '/images/faker/87.jpg',
                                              '/images/faker/88.jpg',
                                              '/images/faker/89.jpg',
                                              '/images/faker/90.jpg',
                                              '/images/faker/91.jpg',
                                              '/images/faker/92.jpg',
                                              '/images/faker/93.jpg',
                                              '/images/faker/94.jpg',
                                              '/images/faker/95.jpg',
                                              '/images/faker/96.jpg',
                                              '/images/faker/97.jpg',
                                              '/images/faker/98.jpg',
                                              '/images/faker/99.jpg',
                                              '/images/faker/100.jpg',
                                              '/images/faker/101.jpg',
                                              '/images/faker/102.jpg',
                                            ]),
            "nb_vote" => fake()->numberBetween(30,1500),
            "note" => fake()->numberBetween(0,5),
        ];
    }
}
